[service.home1]
hierarchy = "/org/freedesktop/home1"
id = "org.freedesktop.home1"
module = "home1"

[service.hostname1]
default_object = "Hostnamed"
hierarchy = "/org/freedesktop/hostname1"
id = "org.freedesktop.hostname1"
module = "hostname1"

[service.import1]
hierarchy = "/org/freedesktop/import1"
id = "org.freedesktop.import1"
module = "import1"
[[service.import1.overrides]]
interface = "org.freedesktop.import1.Transfer"
todo_properties = ["Type"]

[service.locale1]
default_object = "Localed"
hierarchy = "/org/freedesktop/locale1"
id = "org.freedesktop.locale1"
module = "locale1"

[service.login1]
hierarchy = "/org/freedesktop/login1"
id = "org.freedesktop.login1"
module = "login1"
[[service.login1.overrides]]
interface = "org.freedesktop.login1.Manager"
todo_properties = ["EnableWallMessages", "WallMessage"]
[[service.login1.overrides]]
interface = "org.freedesktop.login1.Session"
todo_properties = ["Type"]

[service.machine1]
hierarchy = "/org/freedesktop/machine1"
id = "org.freedesktop.machine1"
module = "machine1"
[[service.machine1.overrides]]
interface = "org.freedesktop.machine1.Machine"
todo_methods = ["GetOSRelease"]
[[service.machine1.overrides]]
interface = "org.freedesktop.machine1.Manager"
todo_methods = [
    "GetMachineOSRelease",
    "GetImageMachineInfo",
    "GetImageOSRelease",
]

[service.oom1]
hierarchy = "/org/freedesktop/oom1"
id = "org.freedesktop.oom1"
module = "oom1"

[service.portable1]
hierarchy = "/org/freedesktop/portable1"
id = "org.freedesktop.portable1"
module = "portable1"
[[service.portable1.overrides]]
interface = "org.freedesktop.portable1.Manager"
todo_methods = [
    "GetImageOSRelease",
    "GetImageMetadata",
    "GetImageMetadataWithExtensions",
]
[[service.portable1.overrides]]
interface = "org.freedesktop.portable1.Image"
todo_methods = ["GetOSRelease", "GetMetadata", "GetMetadataWithExtensions"]
todo_properties = ["Type"]

[service.resolve1]
hierarchy = "/org/freedesktop/resolve1"
id = "org.freedesktop.resolve1"
module = "resolve1"
[[service.resolve1.overrides]]
interface = "org.freedesktop.resolve1.Manager"
todo_methods = ["ResolveService", "RegisterService"]

[service.systemd1]
hierarchy = "/org/freedesktop/systemd1"
id = "org.freedesktop.systemd1"
module = "systemd1"
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Manager"
todo_properties = [
    "LogLevel",
    "LogTarget",
    "RuntimeWatchdogUSec",
    "RebootWatchdogUSec",
    "KExecWatchdogUSec",
    "ServiceWatchdogs",
    "RuntimeWatchdogPreUSec",
    "RuntimeWatchdogPreGovernor",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Service"
todo_properties = ["ExtensionImages", "MountImages", "LogExtraFields", "Type"]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Socket"
todo_properties = ["ExtensionImages", "MountImages", "LogExtraFields"]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Automount"
todo_properties = ["Where"]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Mount"
todo_properties = [
    "ExtensionImages",
    "MountImages",
    "LogExtraFields",
    "Where",
    "Type",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Swap"
todo_properties = ["ExtensionImages", "LogExtraFields", "MountImages"]

[service.timedate1]
default_object = "Timedated"
hierarchy = "/org/freedesktop/timedate1"
id = "org.freedesktop.timedate1"
module = "timedate1"
